# Generated by Django 3.2.4 on 2021-06-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
    ]
