# Generated by Django 3.2.4 on 2021-07-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_emissao', models.DateField(auto_now_add=True)),
                ('mes_referente', models.CharField(choices=[(1, 'JANEIRO'), (2, 'FEVEREIRO'), (3, 'MARÇO'), (4, 'ABRIL'), (5, 'MAIO'), (6, 'JUNHO'), (7, 'JULHO'), (8, 'SETEMBRO'), (9, 'AGOSTO'), (10, 'OUTUBRO'), (11, 'NOVEMBRO'), (12, 'DEZEMBRO')], max_length=2)),
                ('dt_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('P', 'PAGO'), ('D', 'NÃO PAGO'), ('N', 'NULA')], max_length=2)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula')),
            ],
        ),
    ]
