# Generated by Django 3.2.4 on 2021-07-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_academia_user'),
        ('aluno', '0002_aluno_user'),
        ('matricula', '0003_alter_mensalidade_mes_referente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('A', 'ATIVA'), ('I', 'INATIVA')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('P', 'PAGO'), ('D', 'NÃO PAGO'), ('N', 'NULA')], default='D', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('academia', 'aluno')},
        ),
    ]
