# Generated by Django 3.2.4 on 2021-07-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_auto_20210719_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='ano',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
