# Generated by Django 3.2.4 on 2021-09-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_mensalidade_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
