# Generated by Django 3.2.4 on 2021-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_mensalidade_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='meio_pagamento',
            field=models.CharField(choices=[('CR', 'CARTÃO DE CRÉDITO'), ('CD', 'CARTÃO DE DÉBITO'), ('PIX', 'PIX'), ('BB', 'BOLETO BANCÁRIO'), ('D', 'DINHEIRO')], default='D', max_length=3),
            preserve_default=False,
        ),
    ]
