# Generated by Django 3.2.4 on 2021-09-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0007_mensalidade_meio_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='razao_nulo',
            field=models.CharField(blank=True, choices=[('E', 'ESTORNO')], max_length=3, null=True),
        ),
    ]
