# Generated by Django 3.2.4 on 2021-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_mensalidade_razao_nulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='razao_nulo',
            field=models.CharField(blank=True, choices=[('ESTORNO', 'A mensalidade foi estornada pelo gerente da academia.'), ('ERRO_CONTABIL', 'A mensalidade foi nula por erro contabil do gerente.')], max_length=50, null=True),
        ),
    ]
