# Generated by Django 3.2.4 on 2021-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
