# Generated by Django 3.2.4 on 2021-08-13 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('braco_direito', models.FloatField(blank=True, null=True)),
                ('braco_esquerdo', models.FloatField(blank=True, null=True)),
                ('antebraco_direito', models.FloatField(blank=True, null=True)),
                ('antebraco_esquerdo', models.FloatField(blank=True, null=True)),
                ('ombro', models.FloatField(blank=True, null=True)),
                ('peitoral', models.FloatField(blank=True, null=True)),
                ('abdome', models.FloatField(blank=True, null=True)),
                ('cintura', models.FloatField(blank=True, null=True)),
                ('gluteo', models.FloatField(blank=True, null=True)),
                ('coxa_direita', models.FloatField(blank=True, null=True)),
                ('coxa_esquerda', models.FloatField(blank=True, null=True)),
                ('panturrilha_direta', models.FloatField(blank=True, null=True)),
                ('panturrilha_esquerda', models.FloatField(blank=True, null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
    ]
