# Generated by Django 3.2.4 on 2021-08-16 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_medicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoes',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicoes',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
    ]
