# Generated by Django 3.2.4 on 2021-08-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_auto_20210816_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicoes',
            new_name='Medicao',
        ),
    ]
