# Generated by Django 3.2.4 on 2021-08-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_rename_medicoes_medicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
